name: SUP Switzerland
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005e65'
    - '#fbfcfe'
    - '#042922'
    - '#758d83'
    - '#ddb499'
  brandStrength: 0
  lightness: 0.9427055490668863
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
